### Create a Notebook
POST http://localhost:3000/api/notebooks
Content-Type: application/json

{
    "title": "Sample Notebook 2",
    "body": "This is the body of the sample notebook."
}

### Fetch All Notebooks
GET http://localhost:3000/api/notebooks

### Fetch a Notebook by ID
GET http://localhost:3000/api/notebooks/25d5656e-2a8e-4317-bf7a-1d0b58de9d5b

### Update a Notebook by ID
PUT http://localhost:3000/api/notebooks/25d5656e-2a8e-4317-bf7a-1d0b58de9d5b
Content-Type: application/json

{
    "title": "Updated Title",
    "body": "Updated body of the notebook."
}

### Delete a Notebook by ID
DELETE http://localhost:3000/api/notebooks/ede90420-78a4-45b2-8b8e-7c5638a4be4c
