### Create a Notebook
POST http://localhost:3000/api/notebooks
Content-Type: application/json

{
    "title": "Sample Notebook nature6",
    "body": "This is the body of the sample notebook."
}

### Fetch All Notebooks
GET http://localhost:3000/api/notebooks

### Fetch a Notebook by ID
GET http://localhost:3000/api/notebooks/25d5656e-2a8e-4317-bf7a-1d0b58de9d5b

### Update a Notebook by ID
PUT http://localhost:3000/api/notebooks/25d5656e-2a8e-4317-bf7a-1d0b58de9d5b
Content-Type: application/json

{
    "title": "Updated Title to nature89",
    "body": "Updated body of the notebook."
}

### Delete a Notebook by ID
DELETE http://localhost:3000/api/notebooks/ab461e67-3362-4874-b682-c2a3559ef313
